[general]
library_name = "libcarotid"
output_file_path = "../lib/LibCarotid.jl"
prologue_file_path = "./prologue.jl"
module_name = "LibCarotid"
export_symbol_prefixes = ["carotid_"]
output_ignorelist = [
    "CAROTID_LINKAGE",
    "CAROTID_DEPRECATED",
]

use_julia_native_enum_type = true
print_using_CEnum = false

[codegen]
use_julia_bool = true
opaque_as_mutable_struct = true
use_ccall_macro = true